#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays the data.

# Use awk to process the Apache log file
awk '{ ip[$1][$9]++ } END { for (ip_addr in ip) { for (status_code in ip[ip_addr]) { print ip[ip_addr][status_code], ip_addr, status_code } } }' /path/to/your/apache_log_file.log | sort -rn | head -n 10
