#!/usr/bin/env bash
# Use awk to group visitors by IP and HTTP status code, then sort by occurrence
awk '{count[$1" "$9]++} END {for (entry in count) print count[entry], entry}' apache-access.log | sort -nr
