#!/usr/bin/env bash
# This script displays lines containing the word 'bash' and its PID

ps aux | grep bash | grep -v grep
# The following line is to ignore SC2009 (shellcheck)
# shellcheck disable=SC2009
ps aux | grep bash | grep -v grep | awk '{print $2}'
